version: "2.1"
services:
  backup:
    image: amazon/aws-cli
    command: s3 sync /config s3://$S3_BUCKET/ruby/ --delete --exclude */Cache/* --exclude *.bif --exclude */Tdarr_Server/* --exclude */Tdarr_Node/*
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      S3_BUCKET:
    volumes:
      - ./config:/config
  netlify:
    build: jobs/netlify
    environment:
      NETLIFY_TOKEN:
  qbittorrent:
    build: jobs/qbittorrent
    environment:
      DATA_DIR: /data
      QBT_HOST: 87.101.92.171
      QBT_PORT: 13620
      QBT_USERNAME: admin
      QBT_PASSWORD:
    volumes:
      - ./data:/data
