x-service: &service
  restart: unless-stopped
x-env: &env
  PUID: 1000
  PGID: 1000
  TZ: America/Halifax
version: "2.1"
services:
  caddy:
    <<: *service
    image: caddy
    environment:
      <<: *env
      XDG_DATA_HOME: /etc
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/caddy:/etc/caddy
  guacamole:
    <<: *service
    image: ghcr.io/linuxserver/guacd
    environment:
      <<: *env
    ports:
      - 4822:4822
  calibre-desktop:
    <<: *service
    image: ghcr.io/linuxserver/calibre
    environment:
      <<: *env
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./config/calibre/desktop:/config
      - ./data/books:/books
  calibre-web:
    <<: *service
    image: ghcr.io/linuxserver/calibre-web
    environment:
      <<: *env
      DOCKER_MODS: linuxserver/calibre-web:calibre
    ports:
      - 8083:8083
    volumes:
      - ./config/calibre/web:/config
      - ./data/books:/books
  wireguard:
    <<: *service
    image: ghcr.io/linuxserver/wireguard
    environment:
      <<: *env
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      # Requires ./wireguard/wg0.conf.
      # If `ip -6 address add <...> dev wg0` outputs: "RTNETLINK answers: Permission denied":
      # - Remove v6 address on `Address` line
      # - Remove ::/0 on `AllowedIPs` line
      - ./config/wireguard:/config
      - /lib/modules:/lib/modules
  qbittorrent:
    <<: *service
    image: ghcr.io/linuxserver/qbittorrent
    network_mode: service:wireguard
    environment:
      <<: *env
      # This port needs to be forwarded by the VPN provider.
      WEBUI_PORT: 57419
    volumes:
      - ./config/qbittorrent:/config
      - ./data/torrents:/downloads
  plex:
    <<: *service
    image: ghcr.io/linuxserver/plex
    environment:
      <<: *env
      PLEX_CLAIM:
    ports:
      - 32400:32400
      - 1900:1900/udp
      # This port is used by Avahi, so including it here prevents you from running it on the host.
      # Everything still seems to work fine without it.
      # - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volumes:
      - ./config/plex:/config
      - ./data/torrents:/torrents
      - ./data/torrents/movies:/movies  # Movies are flat.
      - ./tv:/tv                        # TV shows are manually organized with symlinks.
